import 'package:zakat_app/util/country.dart';

final List<Country> countryList = [
  Country(
    isoCode: "AD",
    phoneCode: "376",
    name: "Andorra",
    iso3Code: "AND",
    currencyCode: "EUR",
    currencySymbol: "EUR",
    currencyName: "Euro",
  ),
  Country(
    isoCode: "AE",
    phoneCode: "971",
    name: "United Arab Emirates",
    iso3Code: "ARE",
    currencyCode: "AED",
    currencySymbol: "\u062f.\u0625",
    currencyName: "UAE dirham",
  ),
  Country(
    isoCode: "AF",
    phoneCode: "93",
    name: "Afghanistan",
    iso3Code: "AFG",
    currencyCode: "AFN",
    currencySymbol: "Afs",
    currencyName: "Afghan afghani",
  ),
  Country(
    isoCode: "AG",
    phoneCode: "1-268",
    name: "Antigua and Barbuda",
    iso3Code: "ATG",
    currencyCode: "XCD",
    currencySymbol: "EC\$",
    currencyName: "East Caribbean dollar",
  ),
  Country(
    isoCode: "AI",
    phoneCode: "1-264",
    name: "Anguilla",
    iso3Code: "AIA",
    currencyCode: "XCD",
    currencySymbol: "XCD",
    currencyName: "East Caribbean Dollar",
  ),
  Country(
    isoCode: "AL",
    phoneCode: "355",
    name: "Albania",
    iso3Code: "ALB",
    currencyCode: "ALL",
    currencySymbol: "L",
    currencyName: "Albanian lek",
  ),
  Country(
    isoCode: "AM",
    phoneCode: "374",
    name: "Armenia",
    iso3Code: "AMD",
    currencyCode: "AMD",
    currencySymbol: "L",
    currencyName: "Armenian dram",
  ),
  Country(
    isoCode: "AN",
    phoneCode: "599",
    name: "Netherlands Antilles",
    iso3Code: "AN",
    currencyCode: "ANG",
    currencySymbol: "ANG",
    currencyName: "Curaçao, Sint Maarten	Netherlands Antilles Guilder	",
  ),
  Country(
    isoCode: "AO",
    phoneCode: "244",
    name: "Angola",
    iso3Code: "AGO",
    currencyCode: "AOA",
    currencySymbol: "AOA",
    currencyName: "Angolan Kwanza",
  ),
  Country(
    isoCode: "AQ",
    phoneCode: "672",
    name: "Antarctica",
    iso3Code: "ATA",
    currencyCode: "NIL",
    currencySymbol: "NIL",
    currencyName: "No universal currency, no shopping malls",
  ),
  Country(
    isoCode: "AR",
    phoneCode: "54",
    name: "Argentina",
    iso3Code: "ARG",
    currencyCode: "ARS",
    currencySymbol: "ARS",
    currencyName: "Argentine Peso",
  ),
  Country(
    isoCode: "AS",
    phoneCode: "1-684",
    name: "American Samoa",
    iso3Code: "ASM",
    currencyCode: "USD",
    currencySymbol: "\$",
    currencyName: "US Dollar",
  ),
  Country(
    isoCode: "AT",
    phoneCode: "43",
    name: "Austria",
    iso3Code: "AUT",
    currencyCode: "EUR",
    currencySymbol: "EUR",
    currencyName: "Euro",
  ),
  Country(
    isoCode: "AU",
    phoneCode: "61",
    name: "Australia",
    iso3Code: "AUS",
    currencyCode: "AUD",
    currencySymbol: "\$",
    currencyName: "Australian Dollar",
  ),
  Country(
    isoCode: "AW",
    phoneCode: "297",
    name: "Aruba",
    iso3Code: "ABW",
    currencyCode: "AWG",
    currencySymbol: "AWG",
    currencyName: "	Aruban Florin",
  ),
  Country(
    isoCode: "AX",
    phoneCode: "358",
    name: "Åland Islands",
    iso3Code: "ALA",
    currencyCode: "NIL",
    currencySymbol: "NIL",
    currencyName: "NIL",
  ),
  Country(
    isoCode: "AZ",
    phoneCode: "994",
    name: "Azerbaijan",
    iso3Code: "AZE",
    currencyCode: "AZN",
    currencySymbol: "AZN",
    currencyName: "Azerbaijan Manat	",
  ),
  Country(
    isoCode: "BA",
    phoneCode: "387",
    name: "Bosnia and Herzegovina",
    iso3Code: "BIH",
    currencyCode: "BAM",
    currencySymbol: "BAM",
    currencyName: "Convertible Mark",
  ),
  Country(
    isoCode: "BB",
    phoneCode: "1-246",
    name: "Barbados",
    iso3Code: "BRB",
    currencyCode: "BBD",
    currencySymbol: "BBD",
    currencyName: "Barbados Dollar",
  ),
  Country(
    isoCode: "BD",
    phoneCode: "880",
    name: "Bangladesh",
    iso3Code: "BGD",
    currencyCode: "BDT",
    currencySymbol: "\u09f3",
    currencyName: "Bangladeshi taka",
  ),
  Country(
    isoCode: "BE",
    phoneCode: "32",
    name: "Belgium",
    iso3Code: "BEL",
    currencyCode: "BUR",
    currencySymbol: "BUR",
    currencyName: "Euro replaced Belgium Francs",
  ),
  Country(
    isoCode: "BF",
    phoneCode: "226",
    name: "Burkina Faso",
    iso3Code: "BFA",
    currencyCode: "XOF",
    currencySymbol: "XOF",
    currencyName: "CFA Franc BCEAO",
  ),
  Country(
    isoCode: "BG",
    phoneCode: "359",
    name: "Bulgaria",
    iso3Code: "BGR",
    currencyCode: "BGN",
    currencySymbol: "BGN",
    currencyName: "	Bulgarian Lev",
  ),
  Country(
    isoCode: "BH",
    phoneCode: "973",
    name: "Bahrain",
    iso3Code: "BHR",
    currencyCode: "BHD",
    currencySymbol: "BHD",
    currencyName: "	Bahraini Dinar",
  ),
  Country(
    isoCode: "BI",
    phoneCode: "257",
    name: "Burundi",
    iso3Code: "BDI",
    currencyCode: "BIF",
    currencySymbol: "BIF",
    currencyName: "Burundi Franc",
  ),
  Country(
    isoCode: "BJ",
    phoneCode: "229",
    name: "Benin",
    iso3Code: "BEN",
    currencyCode: "XOF",
    currencySymbol: "XOF",
    currencyName: "CFA Franc BCEAO	",
  ),
  Country(
    isoCode: "BL",
    phoneCode: "590",
    name: "Saint Barthélemy",
    iso3Code: "BLM",
    currencyCode: "BIF",
    currencySymbol: "BIF",
    currencyName: "Burundi Franc",
  ),
  Country(
    isoCode: "BM",
    phoneCode: "1-441",
    name: "Bermuda",
    iso3Code: "BMU",
    currencyCode: "BMD",
    currencySymbol: "BMD",
    currencyName: "Bermudian Dollar",
  ),
  Country(
    isoCode: "BN",
    phoneCode: "673",
    name: "Brunei Darussalam",
    iso3Code: "BRN",
    currencyCode: "BND",
    currencySymbol: "BND",
    currencyName: "Brunei Dollar",
  ),
  Country(
    isoCode: "BO",
    phoneCode: "591",
    name: "Bolivia, Plurinational State of",
    iso3Code: "BOL",
    currencyCode: "BOB",
    currencySymbol: "BOB",
    currencyName: "Boliviano",
  ),
  Country(
    isoCode: "BQ",
    phoneCode: "599",
    name: "Caribbean Netherlands",
    iso3Code: "BES",
    currencyCode: "NUL",
    currencySymbol: "NUL",
    currencyName: "NUL",
  ),
  Country(
    isoCode: "BR",
    phoneCode: "55",
    name: "Brazil",
    iso3Code: "BRA",
    currencyCode: "BRL",
    currencySymbol: "BRL",
    currencyName: "	Brazilian Real",
  ),
  Country(
    isoCode: "BS",
    phoneCode: "1-242",
    name: "Bahamas",
    iso3Code: "BHS",
    currencyCode: "BSD",
    currencySymbol: "BSD",
    currencyName: "Bahamian Dollar",
  ),
  Country(
    isoCode: "BT",
    phoneCode: "975",
    name: "Bhutan",
    iso3Code: "BTN",
    currencyCode: "BTN",
    currencySymbol: "BTN",
    currencyName: "Bhutanese Ngultrum Indian Rupee",
  ),
  Country(
    isoCode: "BV",
    phoneCode: "47",
    name: "Bouvet Island",
    iso3Code: "BVT",
    currencyCode: "NUL",
    currencySymbol: "NUL",
    currencyName: "NUL",
  ),
  Country(
    isoCode: "BW",
    phoneCode: "267",
    name: "Botswana",
    iso3Code: "BWA",
    currencyCode: "BWP",
    currencySymbol: "BWP",
    currencyName: "Pula",
  ),
  Country(
    isoCode: "BY",
    phoneCode: "375",
    name: "Belarus",
    iso3Code: "BLR",
    currencyCode: "BYR",
    currencySymbol: "BYR",
    currencyName: "Belarusian Ruble",
  ),
  Country(
    isoCode: "BZ",
    phoneCode: "501",
    name: "Belize",
    iso3Code: "BLZ",
    currencyCode: "BZD",
    currencySymbol: "BZD",
    currencyName: "	Belize Dollar",
  ),
  Country(
    isoCode: "CA",
    phoneCode: "1",
    name: "Canada",
    iso3Code: "CAN",
    currencyCode: "CAD",
    currencySymbol: "CAD",
    currencyName: "Canadian Dollar	",
  ),
  Country(
    isoCode: "CC",
    phoneCode: "61",
    name: "Cocos (Keeling) Islands",
    iso3Code: "CCK",
    currencyCode: "AUD",
    currencySymbol: "AUD",
    currencyName: "Islands	Australian Dollar",
  ),
  Country(
    isoCode: "CD",
    phoneCode: "243",
    name: "Congo, the Democratic Republic of the",
    iso3Code: "COD",
    currencyCode: "CDF",
    currencySymbol: "CDF",
    currencyName: "Franc Congolais	",
  ),
  Country(
    isoCode: "CF",
    phoneCode: "236",
    name: "Central African Republic",
    iso3Code: "CAF",
    currencyCode: "XAF",
    currencySymbol: "XAF",
    currencyName: "CFA Franc BEAC	",
  ),
  Country(
    isoCode: "CG",
    phoneCode: "242",
    name: "Congo",
    iso3Code: "COG",
    currencyCode: "XAF",
    currencySymbol: "XAF",
    currencyName: "CFA Franc BEAC		",
  ),
  Country(
    isoCode: "CH",
    phoneCode: "41",
    name: "Switzerland",
    iso3Code: "CHE",
    currencyCode: "CHF",
    currencySymbol: "CHF",
    currencyName: "Swiss Franc	",
  ),
  Country(
    isoCode: "CI",
    phoneCode: "225",
    name: "Côte d'Ivoire",
    iso3Code: "CIV",
    currencyCode: "NUL",
    currencySymbol: "NUL",
    currencyName: "NUL",
  ),
  Country(
    isoCode: "CK",
    phoneCode: "682",
    name: "Cook Islands",
    iso3Code: "COK",
    currencyCode: "NZD",
    currencySymbol: "NZD",
    currencyName: "New Zealand Dollar	",
  ),
  Country(
    isoCode: "CL",
    phoneCode: "56",
    name: "Chile",
    iso3Code: "CHL",
    currencyCode: "CLP",
    currencySymbol: "CLP",
    currencyName: "Chilean Peso	",
  ),
  Country(
    isoCode: "CM",
    phoneCode: "237",
    name: "Cameroon",
    iso3Code: "CMR",
    currencyCode: "XAF",
    currencySymbol: "XAF",
    currencyName: "CFA Franc BEAC	",
  ),
  Country(
    isoCode: "CN",
    phoneCode: "86",
    name: "China",
    iso3Code: "CHN",
    currencyCode: "CNY",
    currencySymbol: "CNY",
    currencyName: "Renminbi (Yuan)	",
  ),
  Country(
    isoCode: "CO",
    phoneCode: "57",
    name: "Colombia",
    iso3Code: "COL",
    currencyCode: "COP",
    currencySymbol: "COP",
    currencyName: "Colombian Peso	",
  ),
  Country(
    isoCode: "CR",
    phoneCode: "506",
    name: "Costa Rica",
    iso3Code: "CRI",
    currencyCode: "CRC",
    currencySymbol: "CRC",
    currencyName: "Costa Rican Colón	",
  ),
  Country(
    isoCode: "CU",
    phoneCode: "53",
    name: "Cuba",
    iso3Code: "CUB",
    currencyCode: "CUP",
    currencySymbol: "CUP",
    currencyName: "Cuban Peso		",
  ),
  Country(
    isoCode: "CV",
    phoneCode: "238",
    name: "Cape Verde",
    iso3Code: "CPV",
    currencyCode: "CVE",
    currencySymbol: "CVE",
    currencyName: "Cape Verde Escudo		",
  ),
  Country(
    isoCode: "CW",
    phoneCode: "599",
    name: "Curaçao",
    iso3Code: "CUW",
    currencyCode: "NUL",
    currencySymbol: "NUL",
    currencyName: "NUL",
  ),
  Country(
    isoCode: "CX",
    phoneCode: "61",
    name: "Christmas Island",
    iso3Code: "CXR",
    currencyCode: "AUD",
    currencySymbol: "AUD",
    currencyName: "Australian Dollar	",
  ),
  Country(
    isoCode: "CY",
    phoneCode: "357",
    name: "Cyprus",
    iso3Code: "CYP",
    currencyCode: "TRY",
    currencySymbol: "TRY",
    currencyName: "Turkish lira	",
  ),
  Country(
    isoCode: "CZ",
    phoneCode: "420",
    name: "Czech Republic",
    iso3Code: "CZE",
    currencyCode: "CZK",
    currencySymbol: "CZK",
    currencyName: "Czech Koruna	",
  ),
  Country(
    isoCode: "DE",
    phoneCode: "49",
    name: "Germany",
    iso3Code: "DEU",
    currencyCode: "DEM",
    currencySymbol: "DEM",
    currencyName: "Euro replaced Deutsche Mark	EUR ",
  ),
  Country(
    isoCode: "DJ",
    phoneCode: "253",
    name: "Djibouti",
    iso3Code: "DJI",
    currencyCode: "DJF",
    currencySymbol: "DJF",
    currencyName: "	Djibouti Franc",
  ),
  Country(
    isoCode: "DK",
    phoneCode: "45",
    name: "Denmark",
    iso3Code: "DNK",
    currencyCode: "DKK",
    currencySymbol: "DKK",
    currencyName: "Danish Kroner",
  ),
  Country(
    isoCode: "DM",
    phoneCode: "1-767",
    name: "Dominica",
    iso3Code: "DMA",
    currencyCode: "XCD",
    currencySymbol: "XCD",
    currencyName: "East Caribbean Dollar",
  ),
  Country(
    isoCode: "DO",
    phoneCode: "1-849",
    name: "Dominican Republic",
    iso3Code: "DOM",
    currencyCode: "DOP",
    currencySymbol: "DOP",
    currencyName: "Dominican Peso",
  ),
  Country(
    isoCode: "DZ",
    phoneCode: "213",
    name: "Algeria",
    iso3Code: "DZA",
    currencyCode: "DZD",
    currencySymbol: "DZD",
    currencyName: "	Algerian Dinar	",
  ),
  Country(
    isoCode: "EC",
    phoneCode: "593",
    name: "Ecuador",
    iso3Code: "ECU",
    currencyCode: "USD",
    currencySymbol: "USD",
    currencyName: "US Dollar (plus Ecuadorian centavo coins)",
  ),
  Country(
    isoCode: "EE",
    phoneCode: "372",
    name: "Estonia",
    iso3Code: "EST",
    currencyCode: "",
    currencySymbol: "",
    currencyName: "",
  ),
  Country(
    isoCode: "EG",
    phoneCode: "20",
    name: "Egypt",
    iso3Code: "EGY",
    currencyCode: "EGP",
    currencySymbol: "EGP",
    currencyName: "Egyptian Pound",
  ),
  Country(
    isoCode: "EH",
    phoneCode: "212",
    name: "Western Sahara",
    iso3Code: "ESH",
    currencyCode: "MAD",
    currencySymbol: "MAD",
    currencyName: "Moroccan Dirham	",
  ),
  Country(
    isoCode: "ER",
    phoneCode: "291",
    name: "Eritrea",
    iso3Code: "ERI",
    currencyCode: "ERN",
    currencySymbol: "ERN",
    currencyName: "Nakfa",
  ),
  Country(
    isoCode: "ES",
    phoneCode: "34",
    name: "Spain",
    iso3Code: "ESP",
    currencyCode: "ESP",
    currencySymbol: "ESP",
    currencyName: "Spain	Euro ",
  ),
  Country(
    isoCode: "ET",
    phoneCode: "251",
    name: "Ethiopia",
    iso3Code: "ETH",
    currencyCode: "ETB",
    currencySymbol: "ETB",
    currencyName: "Ethiopian Birr",
  ),
  Country(
    isoCode: "FI",
    phoneCode: "358",
    name: "Finland",
    iso3Code: "FIN",
    currencyCode: "EUR",
    currencySymbol: "EUR",
    currencyName: "Euro replaced Markka",
  ),
  Country(
    isoCode: "FJ",
    phoneCode: "679",
    name: "Fiji",
    iso3Code: "FJI",
    currencyCode: "FJD",
    currencySymbol: "FJD",
    currencyName: "Fiji Dollar",
  ),
  Country(
    isoCode: "FK",
    phoneCode: "500",
    name: "Falkland Islands (Malvinas)",
    iso3Code: "FLK",
    currencyCode: "FKP",
    currencySymbol: "FKP",
    currencyName: "Falkland Islands pound",
  ),
  Country(
    isoCode: "FM",
    phoneCode: "691",
    name: "Micronesia, Federated States of",
    iso3Code: "FSM",
    currencyCode: "USD",
    currencySymbol: "USD",
    currencyName: "US Dollar	",
  ),
  Country(
    isoCode: "FO",
    phoneCode: "298",
    name: "Faroe Islands",
    iso3Code: "FRO",
    currencyCode: "FOK",
    currencySymbol: "FOK",
    currencyName: "Faroese króna",
  ),
  Country(
    isoCode: "FR",
    phoneCode: "33",
    name: "France",
    iso3Code: "FRA",
    currencyCode: "EUR",
    currencySymbol: "EUR",
    currencyName: "	Euro eplaced French Franc",
  ),
  Country(
    isoCode: "GA",
    phoneCode: "241",
    name: "Gabon",
    iso3Code: "GAB",
    currencyCode: "XAF",
    currencySymbol: "XAF",
    currencyName: "CFA Franc BEAC	",
  ),
  Country(
    isoCode: "GB",
    phoneCode: "44",
    name: "United Kingdom",
    iso3Code: "GBR",
    currencyCode: "GBP",
    currencySymbol: "GBP",
    currencyName: "Pound Sterling	",
  ),
  Country(
    isoCode: "GB-ENG",
    phoneCode: "44",
    name: "England",
    iso3Code: "GBR",
    currencyCode: "NUL",
    currencySymbol: "NUL",
    currencyName: "NUL",
  ),
  Country(
    isoCode: "GB-NIR",
    phoneCode: "44",
    name: "Northern Ireland",
    iso3Code: "GBR",
    currencyCode: "NUL",
    currencySymbol: "NUL",
    currencyName: "NUL",
  ),
  Country(
    isoCode: "GB-SCT",
    phoneCode: "44",
    name: "Scotland",
    iso3Code: "GBR",
    currencyCode: "NUL",
    currencySymbol: "NUL",
    currencyName: "NUL",
  ),
  Country(
    isoCode: "GB-WLS",
    phoneCode: "44",
    name: "Wales",
    iso3Code: "GBR",
    currencyCode: "NUL",
    currencySymbol: "NUL",
    currencyName: "NUL",
  ),
  Country(
    isoCode: "GD",
    phoneCode: "1-473",
    name: "Grenada",
    iso3Code: "GRD",
    currencyCode: "XCD",
    currencySymbol: "XCD",
    currencyName: "East Caribbean Dollar	",
  ),
  Country(
    isoCode: "GE",
    phoneCode: "995",
    name: "Georgia",
    iso3Code: "GEO",
    currencyCode: "GEL",
    currencySymbol: "GEL",
    currencyName: "Lari	",
  ),
  Country(
    isoCode: "GF",
    phoneCode: "594",
    name: "French Guiana",
    iso3Code: "GUF",
    currencyCode: "EUR",
    currencySymbol: "EUR",
    currencyName: "Euro",
  ),
  Country(
    isoCode: "GG",
    phoneCode: "44-1481",
    name: "Guernsey",
    iso3Code: "GGY",
    currencyCode: "NUL",
    currencySymbol: "NUL",
    currencyName: "NUL",
  ),
  Country(
    isoCode: "GH",
    phoneCode: "233",
    name: "Ghana",
    iso3Code: "GHA",
    currencyCode: "GHC",
    currencySymbol: "GHC",
    currencyName: "Cedi	",
  ),
  Country(
    isoCode: "GI",
    phoneCode: "350",
    name: "Gibraltar",
    iso3Code: "GIB",
    currencyCode: "GIP",
    currencySymbol: "GIP",
    currencyName: "Gibraltar Pound		",
  ),
  Country(
    isoCode: "GL",
    phoneCode: "299",
    name: "Greenland",
    iso3Code: "GRL",
    currencyCode: "DKK",
    currencySymbol: "DKK",
    currencyName: "Danish Krone	",
  ),
  Country(
    isoCode: "GM",
    phoneCode: "220",
    name: "Gambia",
    iso3Code: "GMB",
    currencyCode: "GMD",
    currencySymbol: "GMD",
    currencyName: "Dalasi	",
  ),
  Country(
    isoCode: "GN",
    phoneCode: "224",
    name: "Guinea",
    iso3Code: "GIN",
    currencyCode: "GNF",
    currencySymbol: "GNF",
    currencyName: "Guinea Franc		",
  ),
  Country(
    isoCode: "GP",
    phoneCode: "590",
    name: "Guadeloupe",
    iso3Code: "GLP",
    currencyCode: "EUR",
    currencySymbol: "EUR",
    currencyName: "Euro	",
  ),
  Country(
    isoCode: "GQ",
    phoneCode: "240",
    name: "Equatorial Guinea",
    iso3Code: "GNQ",
    currencyCode: "XAF",
    currencySymbol: "XAF",
    currencyName: "CFA Franc BEAC",
  ),
  Country(
    isoCode: "GR",
    phoneCode: "30",
    name: "Greece",
    iso3Code: "GRC",
    currencyCode: "EUR",
    currencySymbol: "EUR",
    currencyName: "Euro ",
  ),
  Country(
    isoCode: "GS",
    phoneCode: "500",
    name: "South Georgia and the South Sandwich Islands",
    iso3Code: "SGS",
    currencyCode: "NUL",
    currencySymbol: "NUL",
    currencyName: "NUL",
  ),
  Country(
    isoCode: "GT",
    phoneCode: "502",
    name: "Guatemala",
    iso3Code: "GTM",
    currencyCode: "GTQ",
    currencySymbol: "GTQ",
    currencyName: "Quetzal		",
  ),
  Country(
    isoCode: "GU",
    phoneCode: "1-671",
    name: "Guam",
    iso3Code: "GUM",
    currencyCode: "USD",
    currencySymbol: "USD",
    currencyName: "US Dollar	",
  ),
  Country(
    isoCode: "GW",
    phoneCode: "245",
    name: "Guinea-Bissau",
    iso3Code: "GNB",
    currencyCode: "XOF",
    currencySymbol: "XOF",
    currencyName: "Guinea-Bissau Peso CFA Franc BCEAO	GWP ",
  ),
  Country(
    isoCode: "GY",
    phoneCode: "592",
    name: "Guyana",
    iso3Code: "GUY",
    currencyCode: "GYD",
    currencySymbol: "GYD",
    currencyName: "Guyana Dollar	",
  ),
  Country(
    isoCode: "HK",
    phoneCode: "852",
    name: "Hong Kong",
    iso3Code: "HKG",
    currencyCode: "HKD",
    currencySymbol: "HKD",
    currencyName: "Hong Kong Dollar",
  ),
  Country(
    isoCode: "HM",
    phoneCode: "672",
    name: "Heard Island and McDonald Islands",
    iso3Code: "HMD",
    currencyCode: "NUL",
    currencySymbol: "NUL",
    currencyName: "NUL",
  ),
  Country(
    isoCode: "HN",
    phoneCode: "504",
    name: "Honduras",
    iso3Code: "HND",
    currencyCode: "HNL",
    currencySymbol: "HNL",
    currencyName: "Lempira",
  ),
  Country(
    isoCode: "HR",
    phoneCode: "385",
    name: "Croatia",
    iso3Code: "HRV",
    currencyCode: "HRK",
    currencySymbol: "HRK",
    currencyName: "Croatian Kuna	",
  ),
  Country(
    isoCode: "HT",
    phoneCode: "509",
    name: "Haiti",
    iso3Code: "HTI",
    currencyCode: "HTG",
    currencySymbol: "HTG",
    currencyName: "Haitian Gourde US Dollar",
  ),
  Country(
    isoCode: "HU",
    phoneCode: "36",
    name: "Hungary",
    iso3Code: "HUN",
    currencyCode: "HUF",
    currencySymbol: "HUF",
    currencyName: "Hungary	Forint",
  ),
  Country(
    isoCode: "ID",
    phoneCode: "62",
    name: "Indonesia",
    iso3Code: "IDN",
    currencyCode: "IDR",
    currencySymbol: "IDR",
    currencyName: "Rupiah		",
  ),
  Country(
    isoCode: "IE",
    phoneCode: "353",
    name: "Ireland",
    iso3Code: "IRL",
    currencyCode: "EUR",
    currencySymbol: "EUR",
    currencyName: "Euro replaced Irish Pound (Punt)	 IEP",
  ),
  Country(
    isoCode: "IL",
    phoneCode: "972",
    name: "Israel",
    iso3Code: "ISR",
    currencyCode: "ILS",
    currencySymbol: "ILS",
    currencyName: "New Israeli Sheqel		",
  ),
  Country(
    isoCode: "IM",
    phoneCode: "44-1624",
    name: "Isle of Man",
    iso3Code: "IMN",
    currencyCode: "NUL",
    currencySymbol: "NUL",
    currencyName: "NUL",
  ),
  Country(
    isoCode: "IN",
    phoneCode: "91",
    name: "India",
    iso3Code: "IND",
    currencyCode: "INR",
    currencySymbol: "\u20B9",
    currencyName: "Indian rupee",
  ),
  Country(
    isoCode: "IO",
    phoneCode: "246",
    name: "British Indian Ocean Territory",
    iso3Code: "IOT",
    currencyCode: "NUL",
    currencySymbol: "NUL",
    currencyName: "NUL",
  ),
  Country(
    isoCode: "IQ",
    phoneCode: "964",
    name: "Iraq",
    iso3Code: "IRQ",
    currencyCode: "IQD",
    currencySymbol: "IQD",
    currencyName: "Iraqi Dinar	",
  ),
  Country(
    isoCode: "IR",
    phoneCode: "98",
    name: "Iran, Islamic Republic of",
    iso3Code: "IRN",
    currencyCode: "IRR",
    currencySymbol: "IRR",
    currencyName: "Iranian Rial	",
  ),
  Country(
    isoCode: "IS",
    phoneCode: "354",
    name: "Iceland",
    iso3Code: "ISL",
    currencyCode: "ISK",
    currencySymbol: "ISK",
    currencyName: "Iceland Krona	",
  ),
  Country(
    isoCode: "IT",
    phoneCode: "39",
    name: "Italy",
    iso3Code: "ITA",
    currencyCode: "EUR",
    currencySymbol: "EUR",
    currencyName: "Euro replaced Lira (ITL)	",
  ),
  Country(
    isoCode: "JE",
    phoneCode: "44-1534",
    name: "Jersey",
    iso3Code: "JEY",
    currencyCode: "NUL",
    currencySymbol: "NUL",
    currencyName: "NUL",
  ),
  Country(
    isoCode: "JM",
    phoneCode: "1-876",
    name: "Jamaica",
    iso3Code: "JAM",
    currencyCode: "JMD",
    currencySymbol: "JMD",
    currencyName: "Jamaican Dollar",
  ),
  Country(
    isoCode: "JO",
    phoneCode: "962",
    name: "Jordan",
    iso3Code: "JOR",
    currencyCode: "JOD",
    currencySymbol: "JOD",
    currencyName: "	Jordanian Dinar",
  ),
  Country(
    isoCode: "JP",
    phoneCode: "81",
    name: "Japan",
    iso3Code: "JPN",
    currencyCode: "JPY",
    currencySymbol: "JPY",
    currencyName: "Yen",
  ),
  Country(
    isoCode: "KE",
    phoneCode: "254",
    name: "Kenya",
    iso3Code: "KEN",
    currencyCode: "KES",
    currencySymbol: "KES",
    currencyName: "Kenyan Shilling",
  ),
  Country(
    isoCode: "KG",
    phoneCode: "996",
    name: "Kyrgyzstan",
    iso3Code: "KGZ",
    currencyCode: "KGS",
    currencySymbol: "KGS",
    currencyName: "Som",
  ),
  Country(
    isoCode: "KH",
    phoneCode: "855",
    name: "Cambodia",
    iso3Code: "KHM",
    currencyCode: "KHR",
    currencySymbol: "KHR",
    currencyName: "Cambodian Riel (the US Dollar is the de facto currency)	",
  ),
  Country(
    isoCode: "KI",
    phoneCode: "686",
    name: "Kiribati",
    iso3Code: "KIR",
    currencyCode: "AUD",
    currencySymbol: "AUD",
    currencyName: "Australian Dollar",
  ),
  Country(
    isoCode: "KM",
    phoneCode: "269",
    name: "Comoros",
    iso3Code: "COM",
    currencyCode: "KMF",
    currencySymbol: "KMF",
    currencyName: "Comoro Franc",
  ),
  Country(
    isoCode: "KN",
    phoneCode: "1-869",
    name: "Saint Kitts and Nevis",
    iso3Code: "KNA",
    currencyCode: "XCD",
    currencySymbol: "XCD",
    currencyName: "East Caribbean Dollar	",
  ),
  Country(
    isoCode: "KP",
    phoneCode: "850",
    name: "Korea, Democratic People's Republic of",
    iso3Code: "PRK",
    currencyCode: "KRW",
    currencySymbol: "KRW",
    currencyName: "WON",
  ),
  Country(
    isoCode: "KR",
    phoneCode: "82",
    name: "Korea, Republic of",
    iso3Code: "KOR",
    currencyCode: "KPW",
    currencySymbol: "KPW",
    currencyName: "North Korean Won",
  ),
  Country(
    isoCode: "KW",
    phoneCode: "965",
    name: "Kuwait",
    iso3Code: "KWT",
    currencyCode: "KWD",
    currencySymbol: "KWD",
    currencyName: "Kuwaiti Dinar",
  ),
  Country(
    isoCode: "KY",
    phoneCode: "1-345",
    name: "Cayman Islands",
    iso3Code: "CYM",
    currencyCode: "KYD",
    currencySymbol: "KYD",
    currencyName: "Cayman Islands Dollar	",
  ),
  Country(
    isoCode: "KZ",
    phoneCode: "7",
    name: "Kazakhstan",
    iso3Code: "KAZ",
    currencyCode: "KZT",
    currencySymbol: "KZT",
    currencyName: "Tenge",
  ),
  Country(
    isoCode: "LA",
    phoneCode: "",
    name: "Lao People's Democratic Republic",
    iso3Code: "LAO",
    currencyCode: "LAK",
    currencySymbol: "LAK",
    currencyName: "Kip	",
  ),
  Country(
    isoCode: "LB",
    phoneCode: "961",
    name: "Lebanon",
    iso3Code: "LBN",
    currencyCode: "LBP",
    currencySymbol: "LBP",
    currencyName: "Lebanese Pound	",
  ),
  Country(
    isoCode: "LC",
    phoneCode: "1-758",
    name: "Saint Lucia",
    iso3Code: "LCA",
    currencyCode: "XCD",
    currencySymbol: "XCD",
    currencyName: "East Caribbean Dollar	",
  ),
  Country(
    isoCode: "LI",
    phoneCode: "423",
    name: "Liechtenstein",
    iso3Code: "LIE",
    currencyCode: "CHF",
    currencySymbol: "CHF",
    currencyName: "Swiss Franc	",
  ),
  Country(
    isoCode: "LK",
    phoneCode: "94",
    name: "Sri Lanka",
    iso3Code: "LKA",
    currencyCode: "LKR",
    currencySymbol: "Rs",
    currencyName: "Sri Lankan rupee",
  ),
  Country(
    isoCode: "LR",
    phoneCode: "231",
    name: "Liberia",
    iso3Code: "LBR",
    currencyCode: "LRD",
    currencySymbol: "LRD",
    currencyName: "Liberian Dollar	",
  ),
  Country(
    isoCode: "LS",
    phoneCode: "266",
    name: "Lesotho",
    iso3Code: "LSO",
    currencyCode: "LSL",
    currencySymbol: "LSL",
    currencyName:
        "Loti (plural Maloti). It is equivalent to the South African Rand.	",
  ),
  Country(
    isoCode: "LT",
    phoneCode: "370",
    name: "Lithuania",
    iso3Code: "LTU",
    currencyCode: "LTL",
    currencySymbol: "LTL",
    currencyName: "Euro replaced Lithuanian Litas		",
  ),
  Country(
    isoCode: "LU",
    phoneCode: "352",
    name: "Luxembourg",
    iso3Code: "LUX",
    currencyCode: "EUR",
    currencySymbol: "EUR",
    currencyName: "Euro replaced Luxembourg Franc LUF",
  ),
  Country(
    isoCode: "LV",
    phoneCode: "371",
    name: "Latvia",
    iso3Code: "LVA",
    currencyCode: "EUR",
    currencySymbol: "EUR",
    currencyName: "Euro	",
  ),
  Country(
    isoCode: "LY",
    phoneCode: "218",
    name: "Libya",
    iso3Code: "LBY",
    currencyCode: "LYD",
    currencySymbol: "LYD",
    currencyName: "Lybian Dinar	",
  ),
  Country(
    isoCode: "MA",
    phoneCode: "212",
    name: "Morocco",
    iso3Code: "MAR",
    currencyCode: "MAD",
    currencySymbol: "MAD",
    currencyName: "Moroccan Dirham	",
  ),
  Country(
    isoCode: "MC",
    phoneCode: "377",
    name: "Monaco",
    iso3Code: "MCO",
    currencyCode: "EUR",
    currencySymbol: "EUR",
    currencyName: "Euro		",
  ),
  Country(
    isoCode: "MD",
    phoneCode: "373",
    name: "Moldova, Republic of",
    iso3Code: "MDA",
    currencyCode: "MDL",
    currencySymbol: "MDL",
    currencyName: "Moldovan Leu	",
  ),
  Country(
    isoCode: "ME",
    phoneCode: "382",
    name: "Montenegro",
    iso3Code: "MNE",
    currencyCode: "EUR",
    currencySymbol: "EUR",
    currencyName: "Euro		",
  ),
  Country(
    isoCode: "MF",
    phoneCode: "590",
    name: "Saint Martin",
    iso3Code: "MAF",
    currencyCode: "NUL",
    currencySymbol: "NUL",
    currencyName: "NUL",
  ),
  Country(
    isoCode: "MG",
    phoneCode: "261",
    name: "Madagascar",
    iso3Code: "MDG",
    currencyCode: "MGF",
    currencySymbol: "MGF",
    currencyName: "Malagasy Franc	",
  ),
  Country(
    isoCode: "MH",
    phoneCode: "692",
    name: "Marshall Islands",
    iso3Code: "MHL",
    currencyCode: "USD",
    currencySymbol: "USD",
    currencyName: "US Dollar	",
  ),
  Country(
    isoCode: "MK",
    phoneCode: "389",
    name: "Macedonia, the former Yugoslav Republic of",
    iso3Code: "MKD",
    currencyCode: "MKD",
    currencySymbol: "MKD",
    currencyName: "Macedonian Denar	",
  ),
  Country(
    isoCode: "ML",
    phoneCode: "223",
    name: "Mali",
    iso3Code: "MLI",
    currencyCode: "XOF",
    currencySymbol: "XOF",
    currencyName: "CFA Franc BCEAO	",
  ),
  Country(
    isoCode: "MM",
    phoneCode: "95",
    name: "Myanmar (Burma)",
    iso3Code: "MMR",
    currencyCode: "MMK",
    currencySymbol: "MMK",
    currencyName: "Burmese Kyat		",
  ),
  Country(
    isoCode: "MN",
    phoneCode: "976",
    name: "Mongolia",
    iso3Code: "MNG",
    currencyCode: "MNT",
    currencySymbol: "MNT",
    currencyName: "Mongolia Tughrik (Tugrik, Tugrug, tögrög)	",
  ),
  Country(
    isoCode: "MO",
    phoneCode: "853",
    name: "Macao",
    iso3Code: "MAC",
    currencyCode: "MOP",
    currencySymbol: "MOP",
    currencyName: "Macanese Pataca	",
  ),
  Country(
    isoCode: "MP",
    phoneCode: "1-670",
    name: "Northern Mariana Islands",
    iso3Code: "MNP",
    currencyCode: "USD",
    currencySymbol: "USD",
    currencyName: "US Dollar		",
  ),
  Country(
    isoCode: "MQ",
    phoneCode: "596",
    name: "Martinique",
    iso3Code: "MTQ",
    currencyCode: "EUR",
    currencySymbol: "EUR",
    currencyName: "Euro	",
  ),
  Country(
    isoCode: "MR",
    phoneCode: "222",
    name: "Mauritania",
    iso3Code: "MRT",
    currencyCode: "MRO",
    currencySymbol: "MRO",
    currencyName: "Ouguiya	",
  ),
  Country(
    isoCode: "MS",
    phoneCode: "1-664",
    name: "Montserrat",
    iso3Code: "MSR",
    currencyCode: "XCD",
    currencySymbol: "XCD",
    currencyName: "East Caribbean Dollar	",
  ),
  Country(
    isoCode: "MT",
    phoneCode: "356",
    name: "Malta",
    iso3Code: "MLT",
    currencyCode: "MTL",
    currencySymbol: "MTL",
    currencyName: "Maltese Lira	",
  ),
  Country(
    isoCode: "MU",
    phoneCode: "230",
    name: "Mauritius",
    iso3Code: "MUS",
    currencyCode: "MUR",
    currencySymbol: "MUR",
    currencyName: "Mauritius Rupee	",
  ),
  Country(
    isoCode: "MV",
    phoneCode: "960",
    name: "Maldives",
    iso3Code: "MDV",
    currencyCode: "MVR",
    currencySymbol: "MVR",
    currencyName: "Rufiyaa	",
  ),
  Country(
    isoCode: "MW",
    phoneCode: "265",
    name: "Malawi",
    iso3Code: "MWI",
    currencyCode: "MWK",
    currencySymbol: "MWK",
    currencyName: "Kwacha	",
  ),
  Country(
    isoCode: "MX",
    phoneCode: "52",
    name: "Mexico",
    iso3Code: "MEX",
    currencyCode: "MXN",
    currencySymbol: "MXN",
    currencyName: "Mexican Peso ",
  ),
  Country(
    isoCode: "MY",
    phoneCode: "60",
    name: "Malaysia",
    iso3Code: "MYS",
    currencyCode: "MYR",
    currencySymbol: "MYR",
    currencyName: "Malaysian Ringgit		",
  ),
  Country(
    isoCode: "MZ",
    phoneCode: "258",
    name: "Mozambique",
    iso3Code: "MOZ",
    currencyCode: "MZM",
    currencySymbol: "MZM",
    currencyName: "Mozambican Metical	",
  ),
  Country(
    isoCode: "NA",
    phoneCode: "264",
    name: "Namibia",
    iso3Code: "NAM",
    currencyCode: "ZAR",
    currencySymbol: "ZAR",
    currencyName: "Namibia DollaR South African Rand	NAD ",
  ),
  Country(
    isoCode: "NC",
    phoneCode: "687",
    name: "New Caledonia",
    iso3Code: "XPF",
    currencyCode: "XPF",
    currencySymbol: "XPF",
    currencyName: "CFP Franc (South Pacific Franc)	",
  ),
  Country(
    isoCode: "NE",
    phoneCode: "227",
    name: "Niger",
    iso3Code: "NER",
    currencyCode: "XOF",
    currencySymbol: "XOF",
    currencyName: "West African CFA Franc		",
  ),
  Country(
    isoCode: "NF",
    phoneCode: "672",
    name: "Norfolk Island",
    iso3Code: "NFK",
    currencyCode: "NUL",
    currencySymbol: "NUL",
    currencyName: "NUL",
  ),
  Country(
    isoCode: "NG",
    phoneCode: "234",
    name: "Nigeria",
    iso3Code: "NGA",
    currencyCode: "NGN",
    currencySymbol: "NGN",
    currencyName: "Nigerian Naira	",
  ),
  Country(
    isoCode: "NI",
    phoneCode: "505",
    name: "Nicaragua",
    iso3Code: "NIC",
    currencyCode: "NIO",
    currencySymbol: "NIO",
    currencyName: "Nicaraguan Córdoba (córdoba oro)	",
  ),
  Country(
    isoCode: "NL",
    phoneCode: "31",
    name: "Netherlands",
    iso3Code: "NLD",
    currencyCode: "NLG",
    currencySymbol: "NLG",
    currencyName: "EURO  ",
  ),
  Country(
    isoCode: "NO",
    phoneCode: "47",
    name: "Norway",
    iso3Code: "NOR",
    currencyCode: "NOK",
    currencySymbol: "NOK",
    currencyName: "Norwegian Krone		",
  ),
  Country(
    isoCode: "NP",
    phoneCode: "977",
    name: "Nepal",
    iso3Code: "NPL",
    currencyCode: "NPR",
    currencySymbol: "NPR",
    currencyName: "Nepalese Rupee	",
  ),
  Country(
    isoCode: "NR",
    phoneCode: "674",
    name: "Nauru",
    iso3Code: "NRU",
    currencyCode: "AUD",
    currencySymbol: "AUD",
    currencyName: "Australian Dollar	",
  ),
  Country(
    isoCode: "NU",
    phoneCode: "683",
    name: "Niue",
    iso3Code: "NIU",
    currencyCode: "NZD",
    currencySymbol: "NZD",
    currencyName: "New Zealand Dollar		",
  ),
  Country(
    isoCode: "NZ",
    phoneCode: "64",
    name: "New Zealand",
    iso3Code: "NZL",
    currencyCode: "NZD",
    currencySymbol: "NZD",
    currencyName: "New Zealand Dollar	",
  ),
  Country(
    isoCode: "OM",
    phoneCode: "968",
    name: "Oman",
    iso3Code: "OMN",
    currencyCode: "OMR",
    currencySymbol: "OMR",
    currencyName: "Omani Rial",
  ),
  Country(
    isoCode: "PA",
    phoneCode: "507",
    name: "Panama",
    iso3Code: "PAN",
    currencyCode: "USD",
    currencySymbol: "USD",
    currencyName: "Panamanian Balboa US Dollar	PAB  ",
  ),
  Country(
    isoCode: "PE",
    phoneCode: "51",
    name: "Peru",
    iso3Code: "PER",
    currencyCode: "PEN",
    currencySymbol: "PEN",
    currencyName: "Peruvian (Nuevo) Sol	",
  ),
  Country(
    isoCode: "PF",
    phoneCode: "689",
    name: "French Polynesia",
    iso3Code: "PYF",
    currencyCode: "XPF",
    currencySymbol: "XPF",
    currencyName: "	CFP Franc",
  ),
  Country(
    isoCode: "PG",
    phoneCode: "675",
    name: "Papua New Guinea",
    iso3Code: "PNG",
    currencyCode: "PGK",
    currencySymbol: "PGK",
    currencyName: "Papua New Guinean Kina	",
  ),
  Country(
    isoCode: "PH",
    phoneCode: "63",
    name: "Philippines",
    iso3Code: "PHL",
    currencyCode: "PHP",
    currencySymbol: "PHP",
    currencyName: "Philippine Peso	",
  ),
  Country(
    isoCode: "PK",
    phoneCode: "92",
    name: "Pakistan",
    iso3Code: "PAK",
    currencyCode: "PKR",
    currencySymbol: "Rs.",
    currencyName: "Pakistani rupee",
  ),
  Country(
    isoCode: "PL",
    phoneCode: "48",
    name: "Poland",
    iso3Code: "POL",
    currencyCode: "PLN",
    currencySymbol: "PLN",
    currencyName: "Polish Zloty (złoty)		",
  ),
  Country(
    isoCode: "PM",
    phoneCode: "508",
    name: "Saint Pierre and Miquelon",
    iso3Code: "SPM",
    currencyCode: "NUL",
    currencySymbol: "NUL",
    currencyName: "NUL",
  ),
  Country(
    isoCode: "PN",
    phoneCode: "64",
    name: "Pitcairn",
    iso3Code: "PCN",
    currencyCode: "NZD",
    currencySymbol: "NZD",
    currencyName: "Island	New Zealand Dollar	",
  ),
  Country(
    isoCode: "PR",
    phoneCode: "1-787",
    name: "Puerto Rico",
    iso3Code: "PRI",
    currencyCode: "USD",
    currencySymbol: "USD",
    currencyName: "US Dollar	",
  ),
  Country(
    isoCode: "PS",
    phoneCode: "970",
    name: "Palestine",
    iso3Code: "PSE",
    currencyCode: "EGP",
    currencySymbol: "EGP",
    currencyName: "Egyptian Pound",
  ),
  Country(
    isoCode: "PT",
    phoneCode: "351",
    name: "Portugal",
    iso3Code: "PRT",
    currencyCode: "EUR",
    currencySymbol: "EUR",
    currencyName: "Euro ",
  ),
  Country(
    isoCode: "PW",
    phoneCode: "680",
    name: "Palau",
    iso3Code: "PLW",
    currencyCode: "USD",
    currencySymbol: "USD",
    currencyName: "US Dollar	",
  ),
  Country(
    isoCode: "PY",
    phoneCode: "595",
    name: "Paraguay",
    iso3Code: "PRY",
    currencyCode: "PYG",
    currencySymbol: "PYG",
    currencyName: "Paraguayan Guarani		",
  ),
  Country(
    isoCode: "QA",
    phoneCode: "974",
    name: "Qatar",
    iso3Code: "QAT",
    currencyCode: "QAR",
    currencySymbol: "QAR",
    currencyName: "Qatari Rial",
  ),
  Country(
    isoCode: "RE",
    phoneCode: "262",
    name: "Réunion",
    iso3Code: "REU",
    currencyCode: "EUR",
    currencySymbol: "EUR",
    currencyName: "Euro",
  ),
  Country(
    isoCode: "RO",
    phoneCode: "40",
    name: "Romania",
    iso3Code: "ROU",
    currencyCode: "ROL",
    currencySymbol: "ROL",
    currencyName: "Leu",
  ),
  Country(
    isoCode: "RS",
    phoneCode: "381",
    name: "Serbia",
    iso3Code: "SRB",
    currencyCode: "CSD",
    currencySymbol: "CSD",
    currencyName: "Serbian Dinar  ",
  ),
  Country(
    isoCode: "RU",
    phoneCode: "7",
    name: "Russian Federation",
    iso3Code: "RUS",
    currencyCode: "RUR",
    currencySymbol: "RUR",
    currencyName: "Russian Ruble",
  ),
  Country(
    isoCode: "RW",
    phoneCode: "250",
    name: "Rwanda",
    iso3Code: "RWA",
    currencyCode: "RWF",
    currencySymbol: "RWF",
    currencyName: "Rwanda Franc",
  ),
  Country(
    isoCode: "SA",
    phoneCode: "966",
    name: "Saudi Arabia",
    iso3Code: "SAU",
    currencyCode: "SAR",
    currencySymbol: "SAR",
    currencyName: "Saudi Riyal	",
  ),
  Country(
    isoCode: "SB",
    phoneCode: "677",
    name: "Solomon Islands",
    iso3Code: "SLB",
    currencyCode: "SBD",
    currencySymbol: "SBD",
    currencyName: "Solomon Islands Dollar	",
  ),
  Country(
    isoCode: "SC",
    phoneCode: "248",
    name: "Seychelles",
    iso3Code: "SYC",
    currencyCode: "SCR",
    currencySymbol: "SCR",
    currencyName: "Seychelles Rupee	",
  ),
  Country(
    isoCode: "SD",
    phoneCode: "249",
    name: "Sudan",
    iso3Code: "SDN",
    currencyCode: "SDG",
    currencySymbol: "SDG",
    currencyName: "	Sudanese Dinar",
  ),
  Country(
    isoCode: "SE",
    phoneCode: "46",
    name: "Sweden",
    iso3Code: "SWE",
    currencyCode: "SEK",
    currencySymbol: "SEK",
    currencyName: "Swedish Krona	",
  ),
  Country(
    isoCode: "SG",
    phoneCode: "65",
    name: "Singapore",
    iso3Code: "SGP",
    currencyCode: "SGD",
    currencySymbol: "SGD",
    currencyName: "Singapore Dollar	",
  ),
  Country(
    isoCode: "SH",
    phoneCode: "290",
    name: "Saint Helena, Ascension and Tristan da Cunha",
    iso3Code: "SHN",
    currencyCode: "SHP",
    currencySymbol: "SHP",
    currencyName: "Saint Helena Pound	",
  ),
  Country(
    isoCode: "SI",
    phoneCode: "386",
    name: "Slovenia",
    iso3Code: "SVN",
    currencyCode: "EUR",
    currencySymbol: "EUR",
    currencyName: "EURO",
  ),
  Country(
    isoCode: "SJ",
    phoneCode: "47",
    name: "Svalbard and Jan Mayen Islands",
    iso3Code: "SJM",
    currencyCode: "NUL",
    currencySymbol: "NUL",
    currencyName: "NUL",
  ),
  Country(
    isoCode: "SK",
    phoneCode: "421",
    name: "Slovakia",
    iso3Code: "SVK",
    currencyCode: "EUR",
    currencySymbol: "EUR",
    currencyName: "Euro ",
  ),
  Country(
    isoCode: "SL",
    phoneCode: "232",
    name: "Sierra Leone",
    iso3Code: "SLE",
    currencyCode: "SLL",
    currencySymbol: "SLL",
    currencyName: "Leone	",
  ),
  Country(
    isoCode: "SM",
    phoneCode: "378",
    name: "San Marino",
    iso3Code: "SMR",
    currencyCode: "EUR",
    currencySymbol: "EUR",
    currencyName: "Euro		",
  ),
  Country(
    isoCode: "SN",
    phoneCode: "221",
    name: "Senegal",
    iso3Code: "SEN",
    currencyCode: "XOF",
    currencySymbol: "XOF",
    currencyName: "CFA Franc BCEAO		",
  ),
  Country(
    isoCode: "SO",
    phoneCode: "252",
    name: "Somalia",
    iso3Code: "SOM",
    currencyCode: "SOS",
    currencySymbol: "SOS",
    currencyName: "Somali Shilling	",
  ),
  Country(
    isoCode: "SR",
    phoneCode: "597",
    name: "Suriname",
    iso3Code: "SUR",
    currencyCode: "SRG",
    currencySymbol: "SRG",
    currencyName: "Suriname Guilder	",
  ),
  Country(
    isoCode: "SS",
    phoneCode: "211",
    name: "South Sudan",
    iso3Code: "SSD",
    currencyCode: "SSP",
    currencySymbol: "SSP",
    currencyName: "South Sudanese pound",
  ),
  Country(
    isoCode: "ST",
    phoneCode: "239",
    name: "Sao Tome and Principe",
    iso3Code: "STP",
    currencyCode: "STD",
    currencySymbol: "STD",
    currencyName: "Dobra	",
  ),
  Country(
    isoCode: "SV",
    phoneCode: "503",
    name: "El Salvador",
    iso3Code: "SLV",
    currencyCode: "SVC",
    currencySymbol: "SVC",
    currencyName: "Salvadoran US Dollar",
  ),
  Country(
    isoCode: "SX",
    phoneCode: "1-721",
    name: "Sint Maarten (Dutch part)",
    iso3Code: "SXM",
    currencyCode: "NUL",
    currencySymbol: "NUL",
    currencyName: "NUL",
  ),
  Country(
    isoCode: "SY",
    phoneCode: "963",
    name: "Syrian Arab Republic",
    iso3Code: "SYR",
    currencyCode: "SYP",
    currencySymbol: "SYP",
    currencyName: "Syrian Pound	",
  ),
  Country(
    isoCode: "SZ",
    phoneCode: "268",
    name: "Swaziland",
    iso3Code: "SWZ",
    currencyCode: "SZL",
    currencySymbol: "SZL",
    currencyName: "Lilangeni	",
  ),
  Country(
    isoCode: "TC",
    phoneCode: "1-649",
    name: "Turks and Caicos Islands",
    iso3Code: "TCA",
    currencyCode: "USD",
    currencySymbol: "USD",
    currencyName: "US Dollar	",
  ),
  Country(
    isoCode: "TD",
    phoneCode: "235",
    name: "Chad",
    iso3Code: "TCD",
    currencyCode: "XAF",
    currencySymbol: "XAF",
    currencyName: "CFA Franc BEAC	",
  ),
  Country(
    isoCode: "TF",
    phoneCode: "262",
    name: "French Southern Territories",
    iso3Code: "ATF",
    currencyCode: "EUR",
    currencySymbol: "EUR",
    currencyName: "Euro",
  ),
  Country(
    isoCode: "TG",
    phoneCode: "228",
    name: "Togo",
    iso3Code: "TGO",
    currencyCode: "XOF",
    currencySymbol: "XOF",
    currencyName: "CFA Franc BCEAO	",
  ),
  Country(
    isoCode: "TH",
    phoneCode: "66",
    name: "Thailand",
    iso3Code: "THA",
    currencyCode: "THB",
    currencySymbol: "THB",
    currencyName: "Thai Baht	",
  ),
  Country(
    isoCode: "TJ",
    phoneCode: "992",
    name: "Tajikistan",
    iso3Code: "TJK",
    currencyCode: "TJS",
    currencySymbol: "TJS",
    currencyName: "Somoni	",
  ),
  Country(
    isoCode: "TK",
    phoneCode: "690",
    name: "Tokelau",
    iso3Code: "TKL",
    currencyCode: "NZD",
    currencySymbol: "NZD",
    currencyName: "New Zealand Dollar	",
  ),
  Country(
    isoCode: "TL",
    phoneCode: "670",
    name: "Timor-Leste",
    iso3Code: "TLS",
    currencyCode: "USD",
    currencySymbol: "USD",
    currencyName: "US Dollar	",
  ),
  Country(
    isoCode: "TM",
    phoneCode: "993",
    name: "Turkmenistan",
    iso3Code: "TKM",
    currencyCode: "TMM",
    currencySymbol: "TMM",
    currencyName: "Manat		",
  ),
  Country(
    isoCode: "TN",
    phoneCode: "216",
    name: "Tunisia",
    iso3Code: "TUN",
    currencyCode: "TND",
    currencySymbol: "TND",
    currencyName: "Tunisian Dinar	",
  ),
  Country(
    isoCode: "TO",
    phoneCode: "676",
    name: "Tonga",
    iso3Code: "TON",
    currencyCode: "TOP",
    currencySymbol: "TOP",
    currencyName: "Paʻanga	",
  ),
  Country(
    isoCode: "TR",
    phoneCode: "90",
    name: "Turkey",
    iso3Code: "TUR",
    currencyCode: "TRY",
    currencySymbol: "TRY",
    currencyName: "Turkish Lira (TRL)		",
  ),
  Country(
    isoCode: "TT",
    phoneCode: "1-868",
    name: "Trinidad and Tobago",
    iso3Code: "TTO",
    currencyCode: "TTD",
    currencySymbol: "TTD",
    currencyName: "Trinidad and Tobago Dollar		",
  ),
  Country(
    isoCode: "TV",
    phoneCode: "688",
    name: "Tuvalu",
    iso3Code: "TUV",
    currencyCode: "AUD",
    currencySymbol: "AUD",
    currencyName: "Australian Dollar	",
  ),
  Country(
    isoCode: "TW",
    phoneCode: "886",
    name: "Taiwan",
    iso3Code: "TWN",
    currencyCode: "TWD",
    currencySymbol: "TWD",
    currencyName: "New Taiwan Dollar	",
  ),
  Country(
    isoCode: "TZ",
    phoneCode: "255",
    name: "Tanzania, United Republic of",
    iso3Code: "TZA",
    currencyCode: "TZS",
    currencySymbol: "TZS",
    currencyName: "Tanzanian Shilling	",
  ),
  Country(
    isoCode: "UA",
    phoneCode: "380",
    name: "Ukraine",
    iso3Code: "UKR",
    currencyCode: "UAH",
    currencySymbol: "UAH",
    currencyName: "Ukrainian Hryvnia	",
  ),
  Country(
    isoCode: "UG",
    phoneCode: "256",
    name: "Uganda",
    iso3Code: "UGA",
    currencyCode: "UGX",
    currencySymbol: "UGX",
    currencyName: "Uganda Shilling	",
  ),
  Country(
    isoCode: "UM",
    phoneCode: "1",
    name: "US Minor Outlying Islands",
    iso3Code: "UMI",
    currencyCode: "NUL",
    currencySymbol: "NUL",
    currencyName: "NUL",
  ),
  Country(
    isoCode: "US",
    phoneCode: "1",
    name: "United States",
    iso3Code: "USA",
    currencyCode: "USD",
    currencySymbol: "\$",
    currencyName: "US Dollar ",
  ),
  Country(
    isoCode: "UY",
    phoneCode: "598",
    name: "Uruguay",
    iso3Code: "URY",
    currencyCode: "UYU",
    currencySymbol: "UYU",
    currencyName: "Uruguayan Peso",
  ),
  Country(
    isoCode: "UZ",
    phoneCode: "998",
    name: "Uzbekistan",
    iso3Code: "UZB",
    currencyCode: "UZS",
    currencySymbol: "UZS",
    currencyName: "Uzbekistan Sum	",
  ),
  Country(
    isoCode: "VA",
    phoneCode: "379",
    name: "Holy See (Vatican City State)",
    iso3Code: "VAT",
    currencyCode: "EUR",
    currencySymbol: "EUR",
    currencyName: "	Euro Replaced Lira",
  ),
  Country(
    isoCode: "VC",
    phoneCode: "1-784",
    name: "Saint Vincent and the Grenadines",
    iso3Code: "VCT",
    currencyCode: "XCD",
    currencySymbol: "XCD",
    currencyName: "East Caribbean Dollar	",
  ),
  Country(
    isoCode: "VE",
    phoneCode: "58",
    name: "Venezuela, Bolivarian Republic of",
    iso3Code: "VEN",
    currencyCode: "VEF",
    currencySymbol: "VEF",
    currencyName: "Venezuelan Bolívar	",
  ),
  Country(
    isoCode: "VG",
    phoneCode: "1-284",
    name: "Virgin Islands, British",
    iso3Code: "VGB",
    currencyCode: "USD",
    currencySymbol: "USD",
    currencyName: "US Dollar		",
  ),
  Country(
    isoCode: "VI",
    phoneCode: "1-340",
    name: "Virgin Islands, U.S.",
    iso3Code: "VIR",
    currencyCode: "USD",
    currencySymbol: "USD",
    currencyName: "US Dollar	",
  ),
  Country(
    isoCode: "VN",
    phoneCode: "84",
    name: "Vietnam",
    iso3Code: "VNM",
    currencyCode: "VND",
    currencySymbol: "VND",
    currencyName: "Vietnamese Dong		",
  ),
  Country(
    isoCode: "VU",
    phoneCode: "678",
    name: "Vanuatu",
    iso3Code: "VUT",
    currencyCode: "VUV",
    currencySymbol: "VUV",
    currencyName: "Vanuatu Vatu	",
  ),
  Country(
    isoCode: "WF",
    phoneCode: "681",
    name: "Wallis and Futuna Islands",
    iso3Code: "WLF",
    currencyCode: "XPF",
    currencySymbol: "XPF",
    currencyName: "CFP Franc",
  ),
  Country(
    isoCode: "XK",
    phoneCode: "383",
    name: "Kosovo",
    iso3Code: "KOS",
    currencyCode: "NUL",
    currencySymbol: "NUL",
    currencyName: "NUL",
  ),
  Country(
    isoCode: "WS",
    phoneCode: "685",
    name: "Samoa",
    iso3Code: "WSM",
    currencyCode: "WST",
    currencySymbol: "WST",
    currencyName: "Tala		",
  ),
  Country(
    isoCode: "YE",
    phoneCode: "967",
    name: "Yemen",
    iso3Code: "YEM",
    currencyCode: "YER",
    currencySymbol: "YER",
    currencyName: "Yemeni Rial	",
  ),
  Country(
    isoCode: "YT",
    phoneCode: "262",
    name: "Mayotte",
    iso3Code: "MYT",
    currencyCode: "EUR",
    currencySymbol: "EUR",
    currencyName: "Euro	",
  ),
  Country(
    isoCode: "ZA",
    phoneCode: "27",
    name: "South Africa",
    iso3Code: "ZAF",
    currencyCode: "ZAR",
    currencySymbol: "ZAR",
    currencyName: "Rand	",
  ),
  Country(
    isoCode: "ZM",
    phoneCode: "260",
    name: "Zambia",
    iso3Code: "ZMB",
    currencyCode: "ZMW",
    currencySymbol: "ZMW",
    currencyName: "Zambian Kwacha",
  ),
  Country(
    isoCode: "ZW",
    phoneCode: "263",
    name: "Zimbabwe",
    iso3Code: "ZWE",
    currencyCode: "ZWD",
    currencySymbol: "ZWD",
    currencyName: "Zimbabwe Dollar",
  ),
];
